#!/usr/bin/env php
<?php

require(__DIR__ . '/../autoload.php');
require(__DIR__ . '/iSwift.php');
$config = require(__DIR__ . '/../../console/bootstrap.php');
$config['modules']['Route'] = [
	'class' => 'iSwift\\Module\\PathToAction',
    'prefix_path' => '',
    'suffix' => '',
    'default_controller' => 'Index'
];
$config['components'] = [
	'input' => function(){
        return new iSwift\Base\Input;
    },
    'output' => function() {
    	return new iSwift\Base\Output;
    }
]

$params = require(__DIR__ . '/../../console/params.php');
$application = new iSwift\Application($config);
$application->set('params', $params)->run();